.\" Version: 1.2
.\"
.TH SAPHanaSR-pacemaker.timer 5 "24 Aug 2026" "" "SAPHanaSR"
.\"
.SH NAME
.\"
SAPHanaSR-pacemaker.timer \- delay pacemaker start on boot
.PP
.\"
.SH DESCRIPTION
.\"
SAPHanaSR-pacemaker.timer delays pacemaker start on boot.
.PP
The timer can be used instead of SBD_DELAY_START, if the delay between corosync
and pacemaker start at boot interferes with cluster resource takeover actions.
When using this timer, SBD_DELAY_START=no is needed.
TODO
.\"
.SH RETURN CODES
.\"
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fP enable and check systemd timer SAPHanaSR-pacemaker.timer
.PP
.RS 2
# systemctl enable SAPHanaSR-pacemaker.timer
.br
# systemctl list-unit-files | grep -i SAPHanaSR-pacemaker.timer
.br
# systemctl status SAPHanaSR-pacemaker.timer
.br
# systemd-analyze dot | grep SAPHanaSR-pacemaker.timer
.RE
.PP
\fB*\fP set SBD_DELAY_START
.PP
# cp -a /etc/sysconfig/sbd /etc/sysconfig/sbd.$(date +%s)
.br
# sed s/^SBD_DELAY_START=.*$/SBD_DELAY_START=no/g -i /etc/sysconfig/sbd
.PP
.\"
.SH FILES
.\"
.TP 4
/usr/lib/systemd/system/SAPHanaSR-pacemaker.timer
the timer unit file.
.TP 4
/usr/lib/systemd/system/pacemaker.service
the default pacemaker service unit file.
.PP
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open a
request for the component BC-OP-LNX-SUSE.
.\" TODO Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH REQUIREMENTS
.\"
* SBD_DELAY_START=no in /etc/sysconfig/sbd.
.PP
* The pacemaker service enabled. 
.PP
.\"
.SH SEE ALSO
.\"
\fBsystemctl\fP(8), \fBsbd\fP(8), \fBcrm\fP(8)
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
SAPHanaSR-pacemaker.timer comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
