.\" Version: 1.2
.\"
.TH SAPHanaSR-pacemaker.timer 7 "22 Jul 2026" "" "SAPHanaSR"
.\"
.SH NAME
.\"
SAPHanaSR-pacemaker.timer - TODO
.PP
.\"
.SH DESCRIPTION
.\"
SAPHanaSR-pacemaker.timer TODO
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fP enable and check SAPHanaSR-pacemaker.timer
.PP
.\"
.SH FILES
.\"
.TP 4
/usr/lib/systemd/system/SAPHanaSR-pacemaker.timer
the timer
.TP 4
/usr/lib/systemd/system/pacemaker.service
the pacemaker service to be started
the hdbdaemon PID file.
.PP
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open a
request for the component BC-OP-LNX-SUSE.
.\" TODO Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH REQUIREMENTS
.\"
TODO
.PP
.\"
.SH SEE ALSO
.\"
\fBsystemctl\fP(8) , TODO
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
SAPHanaSR-pacemaker.timer comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"

