.\" Version: 1.2
.\"
.TH SAPHanaSR-prep-for-test 8 "02 Jun 2026" "" "SAPHanaSR"
.\"
.SH NAME
.\"
SAPHanaSR-prep-for-test \- prepare node for cluster tests
.PP
.\"
.SH SYNOPSIS
.\"
\fBSAPHanaSR-prep-for-test [ --help | --version | --force ]
.PP
.\"
.SH DESCRIPTION
.\"
SAPHanaSR-prep-for-test helps preparing a node for cluster tests.
.PP
Automated cluster tests need fenced nodes booting and joining the cluster
automatcally after tests. On the other hand, SAPHanaSR-angi scale-up perf-opt and
scale-out perf-opt default configuration for production described in setup guides
and manual pages recommend to not start the cluster automatically at boot. At
least SBD_STARTMODE=clean should be used.
.PP
SAPHanaSR-prep-for-tests cleans SBD devices and starts the pacemaker cluster at
boot time. This script must not be used on production clusters.
.PP
.\"
.SH OPTIONS
.\"
.TP 4
\fB --help\fR
show help.
.TP 4
\fB --version\fR
show version.
.TP 4
\fB --force\fR
force script execution.
.PP
.\"
.SH RETURN CODES
.\"
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fP enable and check systemd service SAPHanaSR-prep-for-test
.PP
.RS 2
# systemctl enable SAPHanaSR-prep-for-test
.br
# systemctl list-unit-files | grep -i SAPHanaSR-prep-for-test
.br
# systemctl status SAPHanaSR-prep-for-test
.br
# systemd-analyze dot | grep SAPHanaSR-prep-for-test
.RE
.PP
\fB*\fP show script messages 
.PP
.RS 2
# grep SAPHanaSR-prep-for-test /var/log/messages
.RE
.PP
.\"
.SH FILES
.\"
.TP 4
/usr/share/SAPHanaSR/bin/SAPHanaSR-prep-for-test
the script itself.
.TP 
/usr/lib/systemd/system/SAPHanaSR-prep-for-test.service
the default unit file.
.PP
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open a
request for the component BC-OP-LNX-SUSE.
.\" TODO Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH REQUIREMENTS
.\"
\fB*\fP This script must not be used on production clusters.
.PP
\fB*\fP This script should run as systemd service at boot time.
It must not be called while the cluster is running.
.PP
\fB*\fP The systemd service SAPHanaSR-prep-for-test needs to be enabled.
.PP
.\"
.SH SEE ALSO
.\"
\fBsystemctl\fP(8)
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
SAPHanaSR-prep-for-test comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
