.\" Version: 1.2
.\"
.TH SAPHanaSR-pacemaker.timer 5 "24 Aug 2026" "" "SAPHanaSR"
.\"
.SH NAME
.\"
SAPHanaSR-pacemaker.timer \- delay pacemaker start on boot
.PP
.\"
.SH DESCRIPTION
.\"
SAPHanaSR-pacemaker.timer delays pacemaker start on boot
.PP
TODO
.\"
.SH RETURN CODES
.\"
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fP enable and check systemd timer SAPHanaSR-pacemaker.timer
.PP
.RS 2
# systemctl enable SAPHanaSR-pacemaker.timer
.br
# systemctl list-unit-files | grep -i SAPHanaSR-pacemaker.timer
.br
# systemctl status SAPHanaSR-pacemaker.timer
.br
# systemd-analyze dot | grep SAPHanaSR-pacemaker.timer
.RE
.PP
.SH FILES
.\"
.TP 4
/usr/lib/systemd/system/SAPHanaSR-prep-for-test.service
the default unit file.
.PP
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open a
request for the component BC-OP-LNX-SUSE.
.\" TODO Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH REQUIREMENTS
.\"
TODO
.SH SEE ALSO
.\"
\fBsystemctl\fP(8), \fBsbd\fP(8), \fBcrm\fP(8)
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
SAPHanaSR-pacemaker.timer comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
