.\" Version: 1.2
.\"
.TH SAPHanaSR-rmHdbPid 8 "02 Jun 2026" "" "SAPHanaSR"
.\"
.SH NAME
.\"
SAPHanaSR-rmHdbPid \- removes left-over HANA hdbdaemon PID file
.PP
.\"
.SH SYNOPSIS
.\"
\fBSAPHanaSR-rmHdbPid\fR [ --help | --version | --force ]
.PP
.\"
.SH DESCRIPTION
.\"
SAPHanaSR-rmHdbPid can be used to remove HANA hdbdaemon PID files.
This might be useful, if a left-over PID file prevents HANA from starting right
after system boot.
.br
Do not call this script while HANA is running.
.PP
.\"
.SH OPTIONS
.\"
.TP 4
\fB --help\fR
show help.
.TP 4
\fB --version\fR
show version.
.TP 4
\fB --force\fR
force script execution.
.PP
.\"
.SH RETURN CODES
.\"
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.PP
.\"
.SH EXAMPLES
.\"
\fB*\fP enable and check systemd service SAPHanSR-rmHdbPid
.PP
.RS 2
# systemctl enable SAPHanaSR-rmHdbPid
.br
# systemctl list-unit-files | grep -i SAPHanaSR-rmHdbPid
.br
# systemctl status SAPHanaSR-rmHdbPid
.br
# systemd-analyze dot | grep SAPHanaSR-rmHdbPid
.RE
.PP
\fB*\fP show script messages
.PP
.RS 2
# grep SAPHanaSR-rmHdbPid /var/log/messages
.RE
.PP
.\"
.SH FILES
.\"
.TP 4
/usr/share/SAPHanaSR-angi/bin/SAPHanaSR-rmHdbPid
the script itself.
.TP 4
/usr/lib/systemd/system/SAPHanaSR-rmHdbPid.service
the default unit file.
.TP 4
/usr/sap/<SID>/HDB<INO>/<HOST>/lock/hdbdaemon@3<INO>00.pid
the hdbdaemon PID file.
.PP
.\"
.SH BUGS
.\"
In case of any problem, please use your favourite SAP support process to open a
request for the component BC-OP-LNX-SUSE.
.\" TODO Please report any other feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH REQUIREMENTS
.\"
\fB*\fP This script is needed only, when left-over hdbdaemon PID files sporadically
prevent HANA from starting.
.PP
\fB*\fP This script should run as systemd service at boot time.
It must not be called while HANA is running.
.PP
\fB*\fP The systemd service SAPHanaSR-rmHdbPid needs to be enabled.
.PP
\fB*\fP The directory /usr/sap/<SID>/HDB<INO>/<HOST>/lock/ needs to be accessible
at boot time. 
.PP
.\"
.SH SEE ALSO
.\"
\fBsystemctl\fP(8)
.PP
.\"
.SH AUTHORS
.\"
F.Herschel, L.Pinne.
.PP
.\"
.SH COPYRIGHT
.\"
(c) 2026 SUSE LLC
.br
SAPHanaSR-rmHdbPid comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
